export const diccionarioEjercicios: Record<string, string> = {
  "Elevación de rodillas sentado (Pull-In)": "seated knee raise",
  "Elevaciones de piernas en banco plano": "lying leg raise",
  "Elevaciones de piernas en paralelas (Silla del capitán)": "hanging leg raise",
  "Libre en descansos activos": "air bike",
  "Curl araña con barra Z": "spider curl with EZ-bar",
  "Curl con barra Z": "EZ-bar curl",
  "Curl con barra tumbado sobre banco inclinado": "incline bench barbell curl",
  "Curl con barra sentado": "seated barbell curl",
  Bicicleta: "air bike",
  Caminadora: "treadmill running",
  "Dominadas agarre ancho": "wide-grip pull-up",
  "Dominadas tras nuca": "behind-the-neck pull-up",
  "Jalón dorsal a una mano": "one-arm lat pulldown",
  "Remo con barra agarre supino": "reverse-grip barbell row",
  "Aductores en máquina": "machine hip adduction",
  "Búlgaras con mancuerna": "bulgarian split squat with dumbbell",
  "Hip thrust con barra": "barbell hip thrust",
  "Patada de glúteo en polea baja": "cable glute kickback",
  "Press militar con barra": "barbell military press",
  "Elevaciones laterales con mancuernas": "dumbbell lateral raise",
  "Pájaros con mancuernas": "dumbbell rear delt fly",
  "Press Arnold": "arnold press",
  "Press inclinado en Multipower": "smith machine incline bench press",
  "Aperturas en poleas en banco inclinado": "incline cable fly",
  "Press con barra en banco inclinado": "incline barbell bench press",
  "Press inclinado en máquina de discos": "machine incline press",
  "Prensa inclinada": "leg press",
  "Sentadilla frontal con barra": "front barbell squat",
  "Extensiones de cuádriceps en máquina": "leg extension",
  "Zancadas caminando con mancuernas": "walking dumbbell lunge",
  "Encogimientos con barra": "barbell shrug",
  "Remo al mentón con barra Z": "EZ-bar upright row",
  "Face pull en polea": "cable face pull",
  "Encogimientos con mancuernas": "dumbbell shrug",
  "Press francés con barra Z": "EZ-bar french press",
  "Fondos en paralelas": "parallel bar dip",
  "Extensión a una mano en polea alta": "one-arm cable triceps extension",
  "Extensión de tríceps en polea con cuerda": "rope triceps pushdown",
  "Femoral en máquina de pie": "standing leg curl machine",
  "Buenos días con barra y piernas separadas": "barbell good morning",
  "Femoral en máquina sentado": "seated leg curl machine",
  "Peso muerto piernas rígidas con barra": "stiff-legged barbell deadlift",
  "Elevación de gemelo a un pie": "single-leg calf raise",
  "Elevación de gemelos con barra sentado": "seated barbell calf raise",
  "Elevación de gemelos de pie con barra": "standing barbell calf raise",
  "Elevaciones de gemelo tipo burro": "donkey calf raise",
  "Curl invertido con barra": "reverse barbell curl",
  "Curl de muñecas con barra palmas abajo": "barbell wrist curl over bench",
  "Curl de muñeca con barra por detrás de la espalda": "behind-the-back barbell wrist curl",
  "Rodillos de muñeca": "wrist roller",
};
